CREATE TABLE WellBoreInfo (
    WELL_BORE_CODE VARCHAR(255) PRIMARY KEY,
    NPD_WELL_BORE_CODE INT,
    NPD_WELL_BORE_NAME VARCHAR(255),
    WELL_TYPE VARCHAR(50)
);

CREATE TABLE FieldFacilityInfo (
    NPD_FIELD_CODE INT PRIMARY KEY,
    NPD_FIELD_NAME VARCHAR(255),
    NPD_FACILITY_CODE INT,
    NPD_FACILITY_NAME VARCHAR(255)
);

CREATE TABLE ProductionData (
    DATEPRD DATE,
    WELL_BORE_CODE VARCHAR(255),
    NPD_FIELD_CODE INT,
    ON_STREAM_HRS FLOAT,
    AVG_DOWNHOLE_PRESSURE FLOAT,
    AVG_DOWNHOLE_TEMPERATURE FLOAT,
    AVG_DP_TUBING FLOAT,
    AVG_ANNULUS_PRESS FLOAT,
    AVG_CHOKE_SIZE_P FLOAT,
    AVG_CHOKE_UOM VARCHAR(10),
    AVG_WHP_P FLOAT,
    AVG_WHT_P FLOAT,
    DP_CHOKE_SIZE FLOAT,
    BORE_OIL_VOL FLOAT,
    BORE_GAS_VOL FLOAT,
    BORE_WAT_VOL FLOAT,
    BORE_WI_VOL FLOAT,
    FLOW_KIND VARCHAR(50),
    PRIMARY KEY (DATEPRD, WELL_BORE_CODE),
    FOREIGN KEY (WELL_BORE_CODE) REFERENCES WellBoreInfo(WELL_BORE_CODE),
    FOREIGN KEY (NPD_FIELD_CODE) REFERENCES FieldFacilityInfo(NPD_FIELD_CODE)
);